# DATOS PARA LAS PRUEBAS:

# Número    Contrato Nombre
# ##########################
# 22004422  Byron Suarez

# 22004455  Sebastian Rosado

# 22004466  Ramon Cedeño

# 22004477  Gonzalo Fienco

### GET TOKEN
POST {{URL}}/api/bc/token HTTP/1.1
Content-Type: application/json

{
    "userName":"DevCalt2024", 
    "password":"Calt2024"
}

### ENVS
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNhbHRBTkQiLCJuYmYiOjE3MzQ0OTg3NTAsImV4cCI6MTczNDUwMDU1MCwiaWF0IjoxNzM0NDk4NzUwLCJpc3MiOiIqIiwiYXVkIjoiKiJ9.TGdExoZKtFlw3K7c8yFTTn7ps4uxeOOHShD-srLObIM
@URL = https://servicioscalt.andinave.com:9068
@TERMINAL = D00561
@IDENTIFICADOR = 22004455

### GET CONSULT

POST {{URL}}/api/bc/ConsultaDeuda HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "Identificador": "{{IDENTIFICADOR}}",
  "terminal": "{{TERMINAL}}",
  "fecha": "20190106",
  "hora": "235959",
}

### SET PAYMENT

# Este campo lo referenciamos para tener una referencia al momento de reversar el pago
# IMPORTE 100,000,000.00
# 10<-00
@IMPORTE = 2050
# ? Es de suma importancia rescatar el cod_trx de la respuesta ya que sera necesaria para reversar la transaccion
POST {{URL}}/api/bc/InformarPago HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "cod_cliente": "{{IDENTIFICADOR}}",
  "terminal": "{{TERMINAL}}",
  "fecha": "20241217",
  "hora": "181000",
  "importe": {{IMPORTE}}
}
 
### SET REVERT PAYMENT

# ?Este Campo es referenciado desde el pago junto a todas las variables mencionadas en la peticion
@COD_TRX = B9DF593B-A7EB-4139-9A49-D9550090FA9A

POST {{URL}}/api/bc/ReversarPago HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "cod_trx":"{{COD_TRX}}", 
  "cod_cliente": "{{IDENTIFICADOR}}",
  "terminal": "{{TERMINAL}}",
  "fecha": "20190106",
  "hora": "101940",
  "importe": {{IMPORTE}}
}

###
# NOTAS 

# fecha y hora, seran las fechas contables 
# el proveedor estara enviando valor minimo y maximo
# validar los campos ingresados de la capa del dominio del proveedor
# El cambio de mensajes durante la consulta debido a la confucion
# Revision a la interna de la documentacion proporcionada a la empresa recaudadora
# Cambio en la estructura de la consulta ( ya no debe devolver el importe y monto abierto)

# Revisar tiempos de respuesta en la generacion de tokens porque es muy lenta y el procesamiento del tiempo del canal es porpio de ellos y no de nosotros
# Analizisis para plantear el mecanismo de proceso de conciliacion
