# DATOS PARA LAS PRUEBAS:

# Número    Contrato Nombre
############################
# 22004422  Byron Suarez

# 22004455  Sebastian Rosado

# 22004466  Ramon Cedeño

# 22004477  Gonzalo Fienco

https://servicioscalt.andinave.com

### GET TOKEN
POST https://servicioscalt.andinave.com:9068/api/bc/token HTTP/1.1
Content-Type: application/json

{
    "userName":"DevCalt2024", 
    "password":"Calt2024"
}

### GET CONSULT
POST https://servicioscalt.andinave.com:9068/api/bc/ConsultaDeuda HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNhbHRBTkQiLCJuYmYiOjE3MzE2ODY3NzMsImV4cCI6MTczMTY4ODU3MywiaWF0IjoxNzMxNjg2NzczLCJpc3MiOiIqIiwiYXVkIjoiKiJ9.IHbRSMc1K9PcWgVbDPrMV7PzsZ_m5fQ3TCSSxMY-Sr8

{
  "Identificador": "22004477",
  "terminal": "D00561",
  "fecha": "20190106",
  "hora": "101940"
}

