# DATOS PARA LAS PRUEBAS:

# Número    Contrato Nombre
############################
# 22004422  Byron Suarez

# 22004455  Sebastian Rosado

# 22004466  Ramon Cedeño

# 22004477  Gonzalo Fienco

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNhbHRBTkQiLCJuYmYiOjE3MzMyNTc2ODcsImV4cCI6MTczMzI1OTQ4NywiaWF0IjoxNzMzMjU3Njg3LCJpc3MiOiIqIiwiYXVkIjoiKiJ9.FahImgwmfecvDFZt2I14C-QJpHo6OYEsMPN7B3uLcgs

### ENPOINT
@URL = https://servicioscalt.andinave.com:9068

### GET TOKEN
POST {{URL}}/api/bc/token HTTP/1.1
Content-Type: application/json

{
    "userName":"DevCalt2024", 
    "password":"Calt2024"
}

### GET CONSULT
POST {{URL}}/api/bc/ConsultaDeuda HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "Identificador": "22004477",
  "terminal": "D00561",
  "fecha": "20190106",
  "hora": "101940"
}

### SET PAYMENT

POST https://servicioscalt.andinave.com:9068/api/bc/ConsultaDeuda HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "Identificador": "22004477",
  "terminal": "D00561",
  "fecha": "20190106",
  "hora": "101940"
}

