
package com.bolivariano.microservice.agrocalidad.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * WS ISS UP
 * 
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "GenericWSAcqBanred", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/home/yigs/agrocalidad/src/main/resources/wsdl/GenericWSAcqMotorPago.wsdl")
public class GenericWSAcqBanred
    extends Service
{

    private static final URL GENERICWSACQBANRED_WSDL_LOCATION;
    private static final WebServiceException GENERICWSACQBANRED_EXCEPTION;
    private static final QName GENERICWSACQBANRED_QNAME = new QName("http://tempuri.org/", "GenericWSAcqBanred");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/yigs/agrocalidad/src/main/resources/wsdl/GenericWSAcqMotorPago.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERICWSACQBANRED_WSDL_LOCATION = url;
        GENERICWSACQBANRED_EXCEPTION = e;
    }

    public GenericWSAcqBanred() {
        super(__getWsdlLocation(), GENERICWSACQBANRED_QNAME);
    }

    public GenericWSAcqBanred(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERICWSACQBANRED_QNAME, features);
    }

    public GenericWSAcqBanred(URL wsdlLocation) {
        super(wsdlLocation, GENERICWSACQBANRED_QNAME);
    }

    public GenericWSAcqBanred(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERICWSACQBANRED_QNAME, features);
    }

    public GenericWSAcqBanred(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenericWSAcqBanred(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenericWSAcqBanredSoap
     */
    @WebEndpoint(name = "GenericWSAcqBanredSoap")
    public GenericWSAcqBanredSoap getGenericWSAcqBanredSoap() {
        return super.getPort(new QName("http://tempuri.org/", "GenericWSAcqBanredSoap"), GenericWSAcqBanredSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenericWSAcqBanredSoap
     */
    @WebEndpoint(name = "GenericWSAcqBanredSoap")
    public GenericWSAcqBanredSoap getGenericWSAcqBanredSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "GenericWSAcqBanredSoap"), GenericWSAcqBanredSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERICWSACQBANRED_EXCEPTION!= null) {
            throw GENERICWSACQBANRED_EXCEPTION;
        }
        return GENERICWSACQBANRED_WSDL_LOCATION;
    }

}
