
package com.bolivariano.microservice.tuklajem.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "GenericWSAcqBanredSoap", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenericWSAcqBanredSoap {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.bolivariano.microservice.tuklajem.wsdl.BillInquiryRs
     */
    @WebMethod(operationName = "BillInquiry", action = "http://tempuri.org/BillInquiry")
    @WebResult(name = "BillInquiryRs", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public BillInquiryRs billInquiry(
        @WebParam(name = "BillInquiryRq", targetNamespace = "http://tempuri.org/", partName = "parameters")
        BillInquiryRq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bolivariano.microservice.tuklajem.wsdl.BillPaymentRs
     */
    @WebMethod(operationName = "BillPayment", action = "http://tempuri.org/BillPayment")
    @WebResult(name = "BillPaymentRs", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public BillPaymentRs billPayment(
        @WebParam(name = "BillPaymentRq", targetNamespace = "http://tempuri.org/", partName = "parameters")
        BillPaymentRq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bolivariano.microservice.tuklajem.wsdl.BillPaymentReversalRs
     */
    @WebMethod(operationName = "BillPaymentReversal", action = "http://tempuri.org/BillPaymentReversal")
    @WebResult(name = "BillPaymentReversalRs", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public BillPaymentReversalRs billPaymentReversal(
        @WebParam(name = "BillPaymentReversalRq", targetNamespace = "http://tempuri.org/", partName = "parameters")
        BillPaymentReversalRq parameters);

}
